// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ToDoContext))]
    [Migration("20240220155232_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.ToDoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ToDoItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("64a42d96-29f3-4e2b-a8fa-e7047cbf1e52"),
                            Description = "Buy milk, chocolate and bread.",
                            Status = false,
                            Title = "Shopping"
                        },
                        new
                        {
                            Id = new Guid("8a562e7d-3947-4456-b9c7-39d9f7676dad"),
                            Description = "",
                            Status = true,
                            Title = "Finish homework"
                        },
                        new
                        {
                            Id = new Guid("a2fd8096-7770-4897-832b-7cdffd8c7e3c"),
                            Description = "Revise materials for exam, which will happen at 14:00 tomorrow.",
                            Status = false,
                            Title = "Cram at night"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
